name: Continuous Delivery

on: 
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Simulando Delivery
        run: echo "Delivery ok"

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
<<<<<<< Updated upstream
      - name: Simulando Deploy
        run: echo "Deploy ok"
=======
      - name: Download do artefato
        uses: actions/download-artifact@v4
        with:
          name: projetozipado

      - name: Display structure of downloaded files
        run: ls -R 
>>>>>>> Stashed changes
