name: Continuos Integration - Teste

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install fastapi pylint

      - name: Rodar Pylint
        # O comando abaixo ignora erros de importação se a lib não estiver no path
        run: pylint --disable=E0401 $(git ls-files '*.py')
