name: Continuous Delivery - Teste

on: 
  push:
    branches:
      - main
      - teste-deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Simular Build
        run: echo "Build realizado com sucesso" # Teste para forçar o pull request 
