name: Continuous Delivery - Teste

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Simular Build
        run: echo "Build realizado com sucesso"

      - name: Simular Deploy
        run: echo "Deploy realizado com sucesso"