name: CI e CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # 1. CI - Continuos Integration com Pylint
  continuos-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install fastapi pylint
      - name: Rodar Pylint
        run: pylint --disable=all --enable=F,E --disable=E0401 main.py

  # 2. CD - DELIVERY 
  continuos-delivery:
    runs-on: ubuntu-latest
    needs: continuos-integration
    steps:
      - uses: actions/checkout@v4
      - name: Criar Artefato
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado
          path: |
            main.py
            README.md

  # 3. DEPLOY
  deploy:
    runs-on: ubuntu-latest
    needs: continuos-delivery
    steps:
      - name: Download do artefato
        uses: actions/download-artifact@v4
        with:
          name: projetozipado
      - name: Listar arquivos (Simulando Deploy)
        run: ls -R
        
  # 4. DOCKER
  docker:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          buildkitd-flags: --debug
      
      - name: Build
        uses: docker/build-push-action@v7

# 5. Integração com Discord
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Commits
        uses: Sniddl/discord-commits@6bf11a849e2f812133e3f7e5df043d06fd262ee8
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          template: "avatar-with-link"
          include-extras: true

