name: CI com Pylint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install fastapi pylint
      - name: Analisar com Pylint
        # O segredo: apenas erros fatais, ignorando importação não encontrada
        run: |
          pylint --disable=all --enable=F,E --disable=E0401 main.py
